import Head from "next/head";
import { Client } from "@notionhq/client";
import styles from "../styles/Home.module.css";
import Moment from "react-moment";



export default function Home({ data, info }) {
  console.log(info)
  return (
    <div className={styles.container}>
      <Head>
        <title>Notion Viewer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.header}>
        <h1>Homework</h1>
        <h2>
          Today's Date: <Moment format="dddd DD" />
          th <Moment format="MMMM" />
        </h2>
      </div>
      {data.map((post) => (
        console.log(post.id),
        <div key={post.id} className={styles.task}>
          <h3 className={styles.title}>Subject: {post.title}</h3>
          <ul>
            <li>Start Date: {post.date_start}</li>
            <li>Due Date: {post.date_end}</li>
          </ul>
          <div className={styles.tags}>Tags: {post.tag_name}</div>
          <p className={styles.description}>Description: </p>
        </div>
      ))}
    </div>
  );
}


export async function getStaticProps() {
  
  const notion = new Client({
    auth: process.env.NOTION_TOKEN,
  });

  const { results } = await notion.databases.query({
    database_id: process.env.NOTION_DATABASE_ID,
    filter: {
      and: [
        {
          property: "Finished",
          checkbox: {
            equals: false,
          },
        },
        {
          property: "Tags",
          multi_select: {
            does_not_contain: "Finished",
          },
        },
      ],
    },
  });

  const meta = results.map((page) => {
    return {
      //   content: results[0].paragraph.text[0].plain_text,
      id: page.id,
      title: page.properties.Name.title[0].text.content,
      date_start: page.properties.Date.date.start,
      date_end: page.properties.Date.date.end,
      tag_name: page.properties.Tags.multi_select[0].name,
      tag_color: page.properties.Tags.multi_select[0].color,
    };
  });

  const block_id = "a1e83068-1eac-45bf-9cb6-186b9db3409b";
  const res = await notion.blocks.children.list({
    block_id: block_id,
  });

  console.log("res", res);
  
  return {
    props: {
      data: meta,
      info: res,
    },
  };

}
