import Head from "next/head";
import getContent from "../lib/getContent"

export default function Home({data}) {
  console.log(data)
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Notion Homework Viewer</h1>
      </main>
    </div>
  );
}

export async function getStaticProps() {
  const res = await fetch("http://localhost:3000/api/homework")
  const data = await res.json()


  return {
    props: {data}
  }
}
